# Generated by Django 4.2 on 2024-11-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
