# Generated by Django 4.2 on 2024-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
