# Generated by Django 4.2 on 2024-11-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
