# Generated by Django 4.2 on 2024-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_login_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login_user',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
