# Generated by Django 4.2 on 2024-11-11 09:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_login_user_languages_login_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('book_name_hindi', models.CharField(blank=True, max_length=255, null=True)),
                ('book_front_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('book_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('book_details_english', models.TextField(blank=True, null=True)),
                ('book_details_hindi', models.TextField(blank=True, null=True)),
                ('book_price_discount', models.IntegerField()),
                ('book_price', models.FloatField()),
                ('book_keyword_english', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=100)),
                ('book_keyword_hindi', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=100)),
                ('author_data', models.ManyToManyField(blank=True, null=True, to='myapp.author')),
                ('category_data', models.ManyToManyField(blank=True, null=True, to='myapp.category')),
            ],
        ),
    ]
