# Generated by Django 4.2 on 2024-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_admin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='device_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
