# Generated by Django 4.2 on 2024-11-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_login_user_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='video')),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
