# Generated by Django 4.2 on 2024-11-13 12:03

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='hylighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('words', django_mysql.models.ListTextField(models.CharField(max_length=1000), blank=True, null=True, size=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('book_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.books')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_user')),
            ],
        ),
    ]
