# Generated by Django 4.2 on 2024-11-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='book_data',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book_data',
            field=models.ManyToManyField(to='myapp.books'),
        ),
    ]
