# Generated by Django 4.2 on 2024-11-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_wishlist_book_data_wishlist_book_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
    ]
