# Generated by Django 4.2 on 2024-11-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_books_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='purchase',
        ),
    ]
