# Generated by Django 4.2 on 2024-11-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_wishlist_book_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='book_data',
            field=models.ManyToManyField(to='myapp.books'),
        ),
    ]
