# Generated by Django 4.2 on 2024-11-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_books_book_language_books_language_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_keyword_english',
            new_name='book_keywords',
        ),
        migrations.RemoveField(
            model_name='books',
            name='book_keyword_hindi',
        ),
    ]
