# Generated by Django 4.2 on 2024-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_book_keyword_english_books_book_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='book'),
        ),
    ]
