# Generated by Django 4.2 on 2024-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_books_book_free_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_free_demo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
