# Generated by Django 4.2 on 2024-11-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_books_book_free_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_languages',
        ),
    ]
