# Generated by Django 4.2 on 2024-11-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_login_user_password_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
