# Generated by Django 4.2 on 2024-11-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_category_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='book_data',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.books'),
        ),
    ]
