# Generated by Django 4.2 on 2024-11-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_wishlist_book_data_wishlist_book_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='hylighter1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(blank=True, default='[]', null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('book_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.books')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_user')),
            ],
        ),
    ]
