# Generated by Django 4.2 on 2024-11-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_hylighter1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hylighter1',
            name='timestamp',
        ),
    ]
