# Generated by Django 4.2 on 2024-11-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_remove_hylighter1_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
